// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SuperPOS.API.Data;

#nullable disable

namespace SuperPOS.API.Migrations
{
    [DbContext(typeof(SuperPOSDbContext))]
    [Migration("20260409041938_AddRemitos")]
    partial class AddRemitos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<decimal>("AlicuotaIva")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("AplicaIva")
                        .HasColumnType("boolean");

                    b.Property<int>("BanderaEAN")
                        .HasColumnType("integer");

                    b.Property<decimal>("Bonificacion1")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("Bonificacion2")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("Bonificacion3")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("Bonificacion4")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("Bonificacion5")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("CajasPorBulto")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("CantidadVendida")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoProveedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DescripcionCorta")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("EsPesable")
                        .HasColumnType("boolean");

                    b.Property<int?>("FamiliaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("integer");

                    b.Property<int>("IdFamilia")
                        .HasColumnType("integer");

                    b.Property<int>("IdMarca")
                        .HasColumnType("integer");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("integer");

                    b.Property<decimal>("ImpuestoInterno")
                        .HasColumnType("decimal(8,4)");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MargenGanancia")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecioOferta")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Recargo1")
                        .HasColumnType("decimal(8,4)");

                    b.Property<bool>("RequiereFechaVencimiento")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiereNroLote")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiereNroSerie")
                        .HasColumnType("boolean");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("StockDeposito")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("StockMaximo")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("UltimaVenta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UnidadesPorBulto")
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoBarras");

                    b.HasIndex("CodigoInterno");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("Descripcion");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("Activo", "IdDepartamento");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.ArticuloCodigoBarras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodigoBarras");

                    b.HasIndex("IdArticulo");

                    b.ToTable("ArticulosCodigoBarras");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.ArticuloPrecioLista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdArticulo")
                        .HasColumnType("integer");

                    b.Property<int>("IdLista")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PorcentajeAjuste")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdLista", "IdArticulo")
                        .IsUnique();

                    b.ToTable("ArticulosPreciosListas");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.BonificacionRango", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadDesde")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("CantidadHasta")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("integer");

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasColumnType("decimal(8,4)");

                    b.HasKey("Id");

                    b.HasIndex("IdArticulo");

                    b.ToTable("BonificacionesRango");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Caja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdSucursal");

                    b.ToTable("Cajas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            IdSucursal = 1,
                            Nombre = "Caja 1"
                        });
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Celular")
                        .HasColumnType("text");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("text");

                    b.Property<int>("CondicionIva")
                        .HasColumnType("integer");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("DiasVencimientoCtaCte")
                        .HasColumnType("integer");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EsMoroso")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVtoCtaCte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdListaPrecio")
                        .HasColumnType("integer");

                    b.Property<int?>("IdVendedor")
                        .HasColumnType("integer");

                    b.Property<decimal>("LimiteCredito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ListaPrecioId")
                        .HasColumnType("integer");

                    b.Property<string>("Localidad")
                        .HasColumnType("text");

                    b.Property<string>("NombreFantasia")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Provincia")
                        .HasColumnType("text");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("SaldoCtaCte")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<bool>("TieneCtaCte")
                        .HasColumnType("boolean");

                    b.Property<char>("TipoSaldo")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)");

                    b.HasKey("Id");

                    b.HasIndex("Cuit");

                    b.HasIndex("ListaPrecioId");

                    b.HasIndex("RazonSocial");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CondicionIva = 5,
                            Cuit = "00000000000",
                            DiasVencimientoCtaCte = 30,
                            EsMoroso = false,
                            FechaAlta = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdListaPrecio = 1,
                            LimiteCredito = 0m,
                            PorcentajeDescuento = 0m,
                            RazonSocial = "Consumidor Final",
                            SaldoCtaCte = 0m,
                            TieneCtaCte = false,
                            TipoSaldo = 'H'
                        });
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Compra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("LetraFactura")
                        .HasColumnType("text");

                    b.Property<string>("NumeroFactura")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIva")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.CompraDetalle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("ActualizaPrecio")
                        .HasColumnType("boolean");

                    b.Property<decimal>("AlicuotaIva")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Bonificacion")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("integer");

                    b.Property<long>("IdCompra")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecioCostoNeto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdCompra");

                    b.ToTable("ComprasDetalle");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Comprobante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CAE")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CAEVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsFacturaElectronica")
                        .HasColumnType("boolean");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCaja")
                        .HasColumnType("integer");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoComprobante")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int?>("IdUsuarioAnulacion")
                        .HasColumnType("integer");

                    b.Property<char>("Letra")
                        .HasColumnType("character(1)");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("PuntoVenta")
                        .HasColumnType("integer");

                    b.Property<string>("QrAfip")
                        .HasColumnType("text");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIva0")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIva105")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIva21")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdTipoComprobante");

                    b.HasIndex("IdSucursal", "PuntoVenta", "Numero", "Letra")
                        .IsUnique();

                    b.ToTable("Comprobantes");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.ComprobanteDetalle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AlicuotaIva")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("integer");

                    b.Property<long>("IdComprobante")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MontoDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoIva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NroLote")
                        .HasColumnType("text");

                    b.Property<string>("NroSerie")
                        .HasColumnType("text");

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecioUnitarioSinIva")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdComprobante");

                    b.ToTable("ComprobantesDetalle");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.ComprobantePago", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdComprobante")
                        .HasColumnType("bigint");

                    b.Property<int>("IdMedioPago")
                        .HasColumnType("integer");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Referencia")
                        .HasColumnType("text");

                    b.Property<decimal>("Vuelto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdComprobante");

                    b.HasIndex("IdMedioPago");

                    b.ToTable("ComprobantesPago");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.ConfiguracionEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AfipCertificadoPassword")
                        .HasColumnType("text");

                    b.Property<string>("AfipCertificadoPath")
                        .HasColumnType("text");

                    b.Property<bool>("AfipHomologacion")
                        .HasColumnType("boolean");

                    b.Property<string>("BackupRuta")
                        .HasColumnType("text");

                    b.Property<bool>("ControlaStock")
                        .HasColumnType("boolean");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("ImpresoraFiscalModelo")
                        .HasColumnType("text");

                    b.Property<string>("ImpresoraFiscalPuerto")
                        .HasColumnType("text");

                    b.Property<string>("ImpresoraTicketNombre")
                        .HasColumnType("text");

                    b.Property<string>("IngresosBrutos")
                        .HasColumnType("text");

                    b.Property<string>("Localidad")
                        .HasColumnType("text");

                    b.Property<string>("MensajePiePagina")
                        .HasColumnType("text");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreFantasia")
                        .HasColumnType("text");

                    b.Property<bool>("PrecioConIva")
                        .HasColumnType("boolean");

                    b.Property<string>("Provincia")
                        .HasColumnType("text");

                    b.Property<int>("PuntoVenta")
                        .HasColumnType("integer");

                    b.Property<string>("SitioWeb")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionEmpresa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AfipHomologacion = true,
                            ControlaStock = true,
                            Cuit = "00-00000000-0",
                            MensajePiePagina = "¡Gracias por su compra! Vuelva pronto.",
                            NombreEmpresa = "Los Angeles Supermercados",
                            NombreFantasia = "Supermercados Los Angeles",
                            PrecioConIva = true,
                            Provincia = "Buenos Aires",
                            PuntoVenta = 1
                        });
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "General"
                        });
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Familia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdDepartamento");

                    b.ToTable("Familias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            IdDepartamento = 1,
                            Nombre = "General"
                        });
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticulosContados")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("DiferenciaValorizada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("TotalArticulos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.InventarioDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaConteo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("integer");

                    b.Property<int>("IdInventario")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("StockContado")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("StockSistema")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdInventario");

                    b.ToTable("InventariosDetalle");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.ListaPrecio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(8,4)");

                    b.HasKey("Id");

                    b.ToTable("ListasPrecios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Precio público general",
                            EsDefault = true,
                            Nombre = "Minorista",
                            Tipo = 0,
                            Valor = 0m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Precio especial por volumen",
                            EsDefault = false,
                            Nombre = "Mayorista",
                            Tipo = 0,
                            Valor = -10m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Precio para empleados",
                            EsDefault = false,
                            Nombre = "Empleados",
                            Tipo = 0,
                            Valor = -15m
                        });
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Sin marca"
                        });
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.MedioPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiereReferencia")
                        .HasColumnType("boolean");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MediosPago");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Efectivo",
                            RequiereReferencia = false,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Tarjeta de Débito",
                            RequiereReferencia = true,
                            Tipo = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Tarjeta de Crédito",
                            RequiereReferencia = true,
                            Tipo = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "MercadoPago",
                            RequiereReferencia = true,
                            Tipo = 5
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "Transferencia",
                            RequiereReferencia = true,
                            Tipo = 6
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Nombre = "Cuenta Corriente",
                            RequiereReferencia = false,
                            Tipo = 7
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Nombre = "Cheque",
                            RequiereReferencia = true,
                            Tipo = 4
                        });
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.MovimientoCtaCte", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<decimal>("Debe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Haber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer");

                    b.Property<long?>("IdComprobante")
                        .HasColumnType("bigint");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<decimal>("SaldoAcumulado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente", "Fecha");

                    b.ToTable("MovimientosCtaCte");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.OrdenCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEntregaEsperada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaRecepcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int?>("IdUsuarioRecepcion")
                        .HasColumnType("integer");

                    b.Property<int>("NroOrden")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSinIva")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdProveedor");

                    b.ToTable("OrdenesCompra");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.OrdenCompraDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AlicuotaIva")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("CantidadPedida")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("CantidadRecibida")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("integer");

                    b.Property<int>("IdOrdenCompra")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdOrdenCompra");

                    b.ToTable("OrdenesCompraDetalle");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AccesoArticulos")
                        .HasColumnType("boolean");

                    b.Property<bool>("AccesoCaja")
                        .HasColumnType("boolean");

                    b.Property<bool>("AccesoClientes")
                        .HasColumnType("boolean");

                    b.Property<bool>("AccesoCompras")
                        .HasColumnType("boolean");

                    b.Property<bool>("AccesoConfiguracion")
                        .HasColumnType("boolean");

                    b.Property<bool>("AccesoCtaCte")
                        .HasColumnType("boolean");

                    b.Property<bool>("AccesoProveedores")
                        .HasColumnType("boolean");

                    b.Property<bool>("AccesoReportes")
                        .HasColumnType("boolean");

                    b.Property<bool>("AccesoStock")
                        .HasColumnType("boolean");

                    b.Property<bool>("AccesoUsuarios")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsAdministrador")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaximoDescuento")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("PuedeAbrirCaja")
                        .HasColumnType("boolean");

                    b.Property<bool>("PuedeAnularVentas")
                        .HasColumnType("boolean");

                    b.Property<bool>("PuedeCambiarPrecios")
                        .HasColumnType("boolean");

                    b.Property<bool>("PuedeCerrarCaja")
                        .HasColumnType("boolean");

                    b.Property<bool>("PuedeHacerDescuentos")
                        .HasColumnType("boolean");

                    b.Property<bool>("PuedeModificarStock")
                        .HasColumnType("boolean");

                    b.Property<bool>("PuedeVender")
                        .HasColumnType("boolean");

                    b.Property<bool>("PuedeVerCostos")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Perfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccesoArticulos = true,
                            AccesoCaja = true,
                            AccesoClientes = true,
                            AccesoCompras = true,
                            AccesoConfiguracion = true,
                            AccesoCtaCte = true,
                            AccesoProveedores = true,
                            AccesoReportes = true,
                            AccesoStock = true,
                            AccesoUsuarios = true,
                            EsAdministrador = true,
                            MaximoDescuento = 100m,
                            Nombre = "Administrador",
                            PuedeAbrirCaja = true,
                            PuedeAnularVentas = true,
                            PuedeCambiarPrecios = true,
                            PuedeCerrarCaja = true,
                            PuedeHacerDescuentos = true,
                            PuedeModificarStock = true,
                            PuedeVender = true,
                            PuedeVerCostos = true
                        },
                        new
                        {
                            Id = 2,
                            AccesoArticulos = false,
                            AccesoCaja = true,
                            AccesoClientes = true,
                            AccesoCompras = false,
                            AccesoConfiguracion = false,
                            AccesoCtaCte = false,
                            AccesoProveedores = false,
                            AccesoReportes = false,
                            AccesoStock = false,
                            AccesoUsuarios = false,
                            EsAdministrador = false,
                            MaximoDescuento = 10m,
                            Nombre = "Cajero",
                            PuedeAbrirCaja = true,
                            PuedeAnularVentas = false,
                            PuedeCambiarPrecios = false,
                            PuedeCerrarCaja = false,
                            PuedeHacerDescuentos = true,
                            PuedeModificarStock = false,
                            PuedeVender = true,
                            PuedeVerCostos = false
                        },
                        new
                        {
                            Id = 3,
                            AccesoArticulos = true,
                            AccesoCaja = true,
                            AccesoClientes = false,
                            AccesoCompras = true,
                            AccesoConfiguracion = false,
                            AccesoCtaCte = false,
                            AccesoProveedores = false,
                            AccesoReportes = false,
                            AccesoStock = true,
                            AccesoUsuarios = false,
                            EsAdministrador = false,
                            MaximoDescuento = 0m,
                            Nombre = "Repositor",
                            PuedeAbrirCaja = true,
                            PuedeAnularVentas = false,
                            PuedeCambiarPrecios = false,
                            PuedeCerrarCaja = false,
                            PuedeHacerDescuentos = false,
                            PuedeModificarStock = true,
                            PuedeVender = true,
                            PuedeVerCostos = true
                        },
                        new
                        {
                            Id = 4,
                            AccesoArticulos = true,
                            AccesoCaja = true,
                            AccesoClientes = true,
                            AccesoCompras = true,
                            AccesoConfiguracion = false,
                            AccesoCtaCte = true,
                            AccesoProveedores = true,
                            AccesoReportes = true,
                            AccesoStock = true,
                            AccesoUsuarios = false,
                            EsAdministrador = false,
                            MaximoDescuento = 30m,
                            Nombre = "Supervisor",
                            PuedeAbrirCaja = true,
                            PuedeAnularVentas = true,
                            PuedeCambiarPrecios = false,
                            PuedeCerrarCaja = true,
                            PuedeHacerDescuentos = true,
                            PuedeModificarStock = true,
                            PuedeVender = true,
                            PuedeVerCostos = true
                        });
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Celular")
                        .HasColumnType("text");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("text");

                    b.Property<string>("CodigoProveedor")
                        .HasColumnType("text");

                    b.Property<int>("CondicionIva")
                        .HasColumnType("integer");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("DiasEntrega")
                        .HasColumnType("integer");

                    b.Property<int>("DiasVencimientoPago")
                        .HasColumnType("integer");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Localidad")
                        .HasColumnType("text");

                    b.Property<string>("NombreFantasia")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Provincia")
                        .HasColumnType("text");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("SaldoCtaCte")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Cuit");

                    b.HasIndex("RazonSocial");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Remito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("integer");

                    b.Property<int?>("IdCompra")
                        .HasColumnType("integer");

                    b.Property<int?>("IdOrdenCompra")
                        .HasColumnType("integer");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("NroRemito")
                        .HasColumnType("integer");

                    b.Property<string>("NroRemitoExterno")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Transportista")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("Tipo", "NroRemito")
                        .IsUnique();

                    b.ToTable("Remitos");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.RemitoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadRecibida")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("CantidadRemitida")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("integer");

                    b.Property<int>("IdRemito")
                        .HasColumnType("integer");

                    b.Property<string>("LoteNro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdRemito");

                    b.ToTable("RemitosDetalle");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<bool>("EsCentral")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sucursales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            EsCentral = true,
                            Nombre = "Casa Central"
                        });
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.TipoComprobante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviatura")
                        .HasColumnType("text");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("CodigoAfip")
                        .HasColumnType("integer");

                    b.Property<bool>("EsCompra")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsVenta")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiereCAE")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("TiposComprobante");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abreviatura = "FA",
                            Activo = true,
                            CodigoAfip = 1,
                            EsCompra = false,
                            EsVenta = true,
                            Nombre = "Factura A",
                            RequiereCAE = true
                        },
                        new
                        {
                            Id = 2,
                            Abreviatura = "FB",
                            Activo = true,
                            CodigoAfip = 6,
                            EsCompra = false,
                            EsVenta = true,
                            Nombre = "Factura B",
                            RequiereCAE = true
                        },
                        new
                        {
                            Id = 3,
                            Abreviatura = "FC",
                            Activo = true,
                            CodigoAfip = 11,
                            EsCompra = false,
                            EsVenta = true,
                            Nombre = "Factura C",
                            RequiereCAE = true
                        },
                        new
                        {
                            Id = 4,
                            Abreviatura = "NCA",
                            Activo = true,
                            CodigoAfip = 3,
                            EsCompra = false,
                            EsVenta = true,
                            Nombre = "Nota de Crédito A",
                            RequiereCAE = true
                        },
                        new
                        {
                            Id = 5,
                            Abreviatura = "NCB",
                            Activo = true,
                            CodigoAfip = 8,
                            EsCompra = false,
                            EsVenta = true,
                            Nombre = "Nota de Crédito B",
                            RequiereCAE = true
                        },
                        new
                        {
                            Id = 6,
                            Abreviatura = "NCC",
                            Activo = true,
                            CodigoAfip = 13,
                            EsCompra = false,
                            EsVenta = true,
                            Nombre = "Nota de Crédito C",
                            RequiereCAE = true
                        },
                        new
                        {
                            Id = 7,
                            Abreviatura = "TK",
                            Activo = true,
                            EsCompra = false,
                            EsVenta = true,
                            Nombre = "Ticket",
                            RequiereCAE = false
                        },
                        new
                        {
                            Id = 8,
                            Abreviatura = "REM",
                            Activo = true,
                            EsCompra = false,
                            EsVenta = false,
                            Nombre = "Remito",
                            RequiereCAE = false
                        },
                        new
                        {
                            Id = 9,
                            Abreviatura = "PRE",
                            Activo = true,
                            EsCompra = false,
                            EsVenta = false,
                            Nombre = "Presupuesto",
                            RequiereCAE = false
                        });
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.TurnoCaja", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Apertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Cierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("IdCaja")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<decimal>("SaldoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCaja");

                    b.ToTable("TurnosCaja");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdPerfil");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdPerfil = 1,
                            NombreCompleto = "Administrador",
                            NombreUsuario = "admin",
                            PasswordHash = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
                        });
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Zeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Anulada")
                        .HasColumnType("boolean");

                    b.Property<int>("CantidadAnulaciones")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadVentas")
                        .HasColumnType("integer");

                    b.Property<decimal>("DiferenciaArqueo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EfectivoDeclarado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCaja")
                        .HasColumnType("integer");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("NroZeta")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAnulaciones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCtaCte")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDescuentos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalEfectivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIva0")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIva105")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIva21")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalMercadoPago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalOtros")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTarjetaCredito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTarjetaDebito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTransferencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalVentas")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCaja", "NroZeta")
                        .IsUnique();

                    b.ToTable("Zetas");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.ZetaDetalleMedio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantOperaciones")
                        .HasColumnType("integer");

                    b.Property<int>("IdMedioPago")
                        .HasColumnType("integer");

                    b.Property<int>("IdZeta")
                        .HasColumnType("integer");

                    b.Property<string>("NombreMedio")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdZeta");

                    b.ToTable("ZetasDetalleMedio");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Articulo", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId");

                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Familia", "Familia")
                        .WithMany()
                        .HasForeignKey("FamiliaId");

                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId");

                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId");

                    b.Navigation("Departamento");

                    b.Navigation("Familia");

                    b.Navigation("Marca");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.ArticuloCodigoBarras", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Articulo", "Articulo")
                        .WithMany("CodigosBarras")
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.ArticuloPrecioLista", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperPOS.Shared.Entities.Ventas.ListaPrecio", "Lista")
                        .WithMany("PreciosEspeciales")
                        .HasForeignKey("IdLista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Lista");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.BonificacionRango", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Caja", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Cliente", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.ListaPrecio", null)
                        .WithMany("Clientes")
                        .HasForeignKey("ListaPrecioId");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Compra", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.CompraDetalle", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Compra", "Compra")
                        .WithMany("Detalles")
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Compra");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Comprobante", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperPOS.Shared.Entities.Ventas.TipoComprobante", "TipoComprobante")
                        .WithMany()
                        .HasForeignKey("IdTipoComprobante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("TipoComprobante");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.ComprobanteDetalle", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Comprobante", "Comprobante")
                        .WithMany("Detalles")
                        .HasForeignKey("IdComprobante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Comprobante");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.ComprobantePago", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Comprobante", "Comprobante")
                        .WithMany("Pagos")
                        .HasForeignKey("IdComprobante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperPOS.Shared.Entities.Ventas.MedioPago", "MedioPago")
                        .WithMany()
                        .HasForeignKey("IdMedioPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comprobante");

                    b.Navigation("MedioPago");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Familia", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Departamento", "Departamento")
                        .WithMany("Familias")
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.InventarioDetalle", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Inventario", "Inventario")
                        .WithMany("Detalles")
                        .HasForeignKey("IdInventario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.MovimientoCtaCte", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.OrdenCompra", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.OrdenCompraDetalle", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperPOS.Shared.Entities.Ventas.OrdenCompra", "OrdenCompra")
                        .WithMany("Detalles")
                        .HasForeignKey("IdOrdenCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("OrdenCompra");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Remito", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.RemitoDetalle", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Remito", "Remito")
                        .WithMany("Detalles")
                        .HasForeignKey("IdRemito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Remito");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.TurnoCaja", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Caja", "Caja")
                        .WithMany()
                        .HasForeignKey("IdCaja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Usuario", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.ZetaDetalleMedio", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Zeta", "Zeta")
                        .WithMany("DetallesMedios")
                        .HasForeignKey("IdZeta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zeta");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Articulo", b =>
                {
                    b.Navigation("CodigosBarras");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Compra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Comprobante", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Departamento", b =>
                {
                    b.Navigation("Familias");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Inventario", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.ListaPrecio", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("PreciosEspeciales");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.OrdenCompra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Remito", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Zeta", b =>
                {
                    b.Navigation("DetallesMedios");
                });
#pragma warning restore 612, 618
        }
    }
}
