// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SuperPOS.API.Data;

#nullable disable

namespace SuperPOS.API.Migrations
{
    [DbContext(typeof(SuperPOSDbContext))]
    [Migration("20260409000231_v1_Supermer")]
    partial class v1_Supermer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<decimal>("AlicuotaIva")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("AplicaIva")
                        .HasColumnType("boolean");

                    b.Property<int>("BanderaEAN")
                        .HasColumnType("integer");

                    b.Property<decimal>("Bonificacion1")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("Bonificacion2")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("Bonificacion3")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("Bonificacion4")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("Bonificacion5")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("CajasPorBulto")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("CantidadVendida")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoProveedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DescripcionCorta")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("EsPesable")
                        .HasColumnType("boolean");

                    b.Property<int?>("FamiliaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("integer");

                    b.Property<int>("IdFamilia")
                        .HasColumnType("integer");

                    b.Property<int>("IdMarca")
                        .HasColumnType("integer");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("integer");

                    b.Property<decimal>("ImpuestoInterno")
                        .HasColumnType("decimal(8,4)");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MargenGanancia")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecioOferta")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Recargo1")
                        .HasColumnType("decimal(8,4)");

                    b.Property<bool>("RequiereFechaVencimiento")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiereNroLote")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiereNroSerie")
                        .HasColumnType("boolean");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("StockDeposito")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("StockMaximo")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("UltimaVenta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UnidadesPorBulto")
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoBarras");

                    b.HasIndex("CodigoInterno");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("Descripcion");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("Activo", "IdDepartamento");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.ArticuloCodigoBarras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodigoBarras");

                    b.HasIndex("IdArticulo");

                    b.ToTable("ArticulosCodigoBarras");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Caja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdSucursal");

                    b.ToTable("Cajas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            IdSucursal = 1,
                            Nombre = "Caja 1"
                        });
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Celular")
                        .HasColumnType("text");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("text");

                    b.Property<int>("CondicionIva")
                        .HasColumnType("integer");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("DiasVencimientoCtaCte")
                        .HasColumnType("integer");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EsMoroso")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVtoCtaCte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdListaPrecio")
                        .HasColumnType("integer");

                    b.Property<int?>("IdVendedor")
                        .HasColumnType("integer");

                    b.Property<decimal>("LimiteCredito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Localidad")
                        .HasColumnType("text");

                    b.Property<string>("NombreFantasia")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Provincia")
                        .HasColumnType("text");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("SaldoCtaCte")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<bool>("TieneCtaCte")
                        .HasColumnType("boolean");

                    b.Property<char>("TipoSaldo")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)");

                    b.HasKey("Id");

                    b.HasIndex("Cuit");

                    b.HasIndex("RazonSocial");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CondicionIva = 5,
                            Cuit = "00000000000",
                            DiasVencimientoCtaCte = 30,
                            EsMoroso = false,
                            FechaAlta = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdListaPrecio = 1,
                            LimiteCredito = 0m,
                            PorcentajeDescuento = 0m,
                            RazonSocial = "Consumidor Final",
                            SaldoCtaCte = 0m,
                            TieneCtaCte = false,
                            TipoSaldo = 'H'
                        });
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Comprobante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CAE")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CAEVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsFacturaElectronica")
                        .HasColumnType("boolean");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCaja")
                        .HasColumnType("integer");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoComprobante")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int?>("IdUsuarioAnulacion")
                        .HasColumnType("integer");

                    b.Property<char>("Letra")
                        .HasColumnType("character(1)");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("PuntoVenta")
                        .HasColumnType("integer");

                    b.Property<string>("QrAfip")
                        .HasColumnType("text");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIva0")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIva105")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIva21")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdTipoComprobante");

                    b.HasIndex("IdSucursal", "PuntoVenta", "Numero", "Letra")
                        .IsUnique();

                    b.ToTable("Comprobantes");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.ComprobanteDetalle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AlicuotaIva")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("integer");

                    b.Property<long>("IdComprobante")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MontoDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoIva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NroLote")
                        .HasColumnType("text");

                    b.Property<string>("NroSerie")
                        .HasColumnType("text");

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecioUnitarioSinIva")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdComprobante");

                    b.ToTable("ComprobantesDetalle");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.ComprobantePago", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdComprobante")
                        .HasColumnType("bigint");

                    b.Property<int>("IdMedioPago")
                        .HasColumnType("integer");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Referencia")
                        .HasColumnType("text");

                    b.Property<decimal>("Vuelto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdComprobante");

                    b.HasIndex("IdMedioPago");

                    b.ToTable("ComprobantesPago");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "General"
                        });
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Familia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdDepartamento");

                    b.ToTable("Familias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            IdDepartamento = 1,
                            Nombre = "General"
                        });
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Sin marca"
                        });
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.MedioPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiereReferencia")
                        .HasColumnType("boolean");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MediosPago");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Efectivo",
                            RequiereReferencia = false,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Tarjeta de Débito",
                            RequiereReferencia = true,
                            Tipo = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Tarjeta de Crédito",
                            RequiereReferencia = true,
                            Tipo = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "MercadoPago",
                            RequiereReferencia = true,
                            Tipo = 5
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "Transferencia",
                            RequiereReferencia = true,
                            Tipo = 6
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Nombre = "Cuenta Corriente",
                            RequiereReferencia = false,
                            Tipo = 7
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Nombre = "Cheque",
                            RequiereReferencia = true,
                            Tipo = 4
                        });
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsAdministrador")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaximoDescuento")
                        .HasColumnType("numeric");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PuedeAbrirCaja")
                        .HasColumnType("boolean");

                    b.Property<bool>("PuedeAnular")
                        .HasColumnType("boolean");

                    b.Property<bool>("PuedeGestionarClientes")
                        .HasColumnType("boolean");

                    b.Property<bool>("PuedeGestionarCompras")
                        .HasColumnType("boolean");

                    b.Property<bool>("PuedeGestionarStock")
                        .HasColumnType("boolean");

                    b.Property<bool>("PuedeHacerDescuentos")
                        .HasColumnType("boolean");

                    b.Property<bool>("PuedeVender")
                        .HasColumnType("boolean");

                    b.Property<bool>("PuedeVerPrecios")
                        .HasColumnType("boolean");

                    b.Property<bool>("PuedeVerReportes")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Perfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EsAdministrador = true,
                            MaximoDescuento = 100m,
                            Nombre = "Administrador",
                            PuedeAbrirCaja = true,
                            PuedeAnular = true,
                            PuedeGestionarClientes = true,
                            PuedeGestionarCompras = true,
                            PuedeGestionarStock = true,
                            PuedeHacerDescuentos = true,
                            PuedeVender = true,
                            PuedeVerPrecios = true,
                            PuedeVerReportes = true
                        },
                        new
                        {
                            Id = 2,
                            EsAdministrador = false,
                            MaximoDescuento = 10m,
                            Nombre = "Cajero",
                            PuedeAbrirCaja = true,
                            PuedeAnular = false,
                            PuedeGestionarClientes = false,
                            PuedeGestionarCompras = false,
                            PuedeGestionarStock = false,
                            PuedeHacerDescuentos = true,
                            PuedeVender = true,
                            PuedeVerPrecios = true,
                            PuedeVerReportes = false
                        });
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Celular")
                        .HasColumnType("text");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("text");

                    b.Property<string>("CodigoProveedor")
                        .HasColumnType("text");

                    b.Property<int>("CondicionIva")
                        .HasColumnType("integer");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("DiasEntrega")
                        .HasColumnType("integer");

                    b.Property<int>("DiasVencimientoPago")
                        .HasColumnType("integer");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Localidad")
                        .HasColumnType("text");

                    b.Property<string>("NombreFantasia")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Provincia")
                        .HasColumnType("text");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("SaldoCtaCte")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Cuit");

                    b.HasIndex("RazonSocial");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<bool>("EsCentral")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sucursales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            EsCentral = true,
                            Nombre = "Casa Central"
                        });
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.TipoComprobante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviatura")
                        .HasColumnType("text");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("CodigoAfip")
                        .HasColumnType("integer");

                    b.Property<bool>("EsCompra")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsVenta")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiereCAE")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("TiposComprobante");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abreviatura = "FA",
                            Activo = true,
                            CodigoAfip = 1,
                            EsCompra = false,
                            EsVenta = true,
                            Nombre = "Factura A",
                            RequiereCAE = true
                        },
                        new
                        {
                            Id = 2,
                            Abreviatura = "FB",
                            Activo = true,
                            CodigoAfip = 6,
                            EsCompra = false,
                            EsVenta = true,
                            Nombre = "Factura B",
                            RequiereCAE = true
                        },
                        new
                        {
                            Id = 3,
                            Abreviatura = "FC",
                            Activo = true,
                            CodigoAfip = 11,
                            EsCompra = false,
                            EsVenta = true,
                            Nombre = "Factura C",
                            RequiereCAE = true
                        },
                        new
                        {
                            Id = 4,
                            Abreviatura = "NCA",
                            Activo = true,
                            CodigoAfip = 3,
                            EsCompra = false,
                            EsVenta = true,
                            Nombre = "Nota de Crédito A",
                            RequiereCAE = true
                        },
                        new
                        {
                            Id = 5,
                            Abreviatura = "NCB",
                            Activo = true,
                            CodigoAfip = 8,
                            EsCompra = false,
                            EsVenta = true,
                            Nombre = "Nota de Crédito B",
                            RequiereCAE = true
                        },
                        new
                        {
                            Id = 6,
                            Abreviatura = "NCC",
                            Activo = true,
                            CodigoAfip = 13,
                            EsCompra = false,
                            EsVenta = true,
                            Nombre = "Nota de Crédito C",
                            RequiereCAE = true
                        },
                        new
                        {
                            Id = 7,
                            Abreviatura = "TK",
                            Activo = true,
                            EsCompra = false,
                            EsVenta = true,
                            Nombre = "Ticket",
                            RequiereCAE = false
                        },
                        new
                        {
                            Id = 8,
                            Abreviatura = "REM",
                            Activo = true,
                            EsCompra = false,
                            EsVenta = false,
                            Nombre = "Remito",
                            RequiereCAE = false
                        },
                        new
                        {
                            Id = 9,
                            Abreviatura = "PRE",
                            Activo = true,
                            EsCompra = false,
                            EsVenta = false,
                            Nombre = "Presupuesto",
                            RequiereCAE = false
                        });
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.TurnoCaja", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Apertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Cierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("IdCaja")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<decimal>("SaldoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCaja");

                    b.ToTable("TurnosCaja");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdPerfil");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdPerfil = 1,
                            NombreCompleto = "Administrador",
                            NombreUsuario = "admin",
                            PasswordHash = "admin"
                        });
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Articulo", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId");

                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Familia", "Familia")
                        .WithMany()
                        .HasForeignKey("FamiliaId");

                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId");

                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId");

                    b.Navigation("Departamento");

                    b.Navigation("Familia");

                    b.Navigation("Marca");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.ArticuloCodigoBarras", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Articulo", "Articulo")
                        .WithMany("CodigosBarras")
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Caja", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Comprobante", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperPOS.Shared.Entities.Ventas.TipoComprobante", "TipoComprobante")
                        .WithMany()
                        .HasForeignKey("IdTipoComprobante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("TipoComprobante");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.ComprobanteDetalle", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Comprobante", "Comprobante")
                        .WithMany("Detalles")
                        .HasForeignKey("IdComprobante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Comprobante");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.ComprobantePago", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Comprobante", "Comprobante")
                        .WithMany("Pagos")
                        .HasForeignKey("IdComprobante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperPOS.Shared.Entities.Ventas.MedioPago", "MedioPago")
                        .WithMany()
                        .HasForeignKey("IdMedioPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comprobante");

                    b.Navigation("MedioPago");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Familia", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Departamento", "Departamento")
                        .WithMany("Familias")
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.TurnoCaja", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Caja", "Caja")
                        .WithMany()
                        .HasForeignKey("IdCaja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Usuario", b =>
                {
                    b.HasOne("SuperPOS.Shared.Entities.Ventas.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Articulo", b =>
                {
                    b.Navigation("CodigosBarras");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Comprobante", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("SuperPOS.Shared.Entities.Ventas.Departamento", b =>
                {
                    b.Navigation("Familias");
                });
#pragma warning restore 612, 618
        }
    }
}
